blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/g6exUXvWge
    about: Join the ASUS TUF Discord server for support and discussions.
  - name: Reddit - Modmail
    url: https://www.reddit.com/message/compose?to=%2Fr/Asustuf&subject=AsusTUF%20Guide%20Contribution%20Request&message=Hello!%20I%20have%20some%20suggestions%20and%20ideas%20for%20the%20guide.%20TYPESUGGESTIONSHERE%20
    about: Contact the subreddit moderators for assistance.