name: Stale issues/PR

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Mark stale issues and PRs
        uses: actions/stale@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 14
          days-before-close: -1
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'qol,typo,correction'
          exempt-pr-labels: 'qol'
          exempt-all-assignees: true
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had any activity in the last 14 days.
            If this issue is still relevant, please comment or update it to prevent it from being closed.
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had any activity in the last 14 days.
            If this pull request is still relevant, please comment or update it to prevent it from being closed.